### PR TITLE
fix: Explicitly set rootDir in server/tsconfig.json to fix TS 6.0 compatibility

### PR DESCRIPTION
**Pull request by kitamura-tetsuo**
This resolves the TS5011 compilation error encountered after upgrading TypeScript from 5.9.3 to 6.0.3. TypeScript 6.0 enforces explicitly defining `rootDir` when the common source directory might not perfectly align with the `outDir` output schema due to included declaration files in adjacent directories. Adding `"rootDir": "./src"` correctly satisfies the compiler requirements.

---
*PR created automatically by Jules for task [8130993198814031362](https://jules.google.com/task/8130993198814031362) started by @kitamura-tetsuo*

### CODE REVIEW

**Comment by kitamura-tetsuo** [comment]
🤖 Auto-Coder: CI checks failed. I've sent the error logs to the Jules session and requested a fix. Please wait for the updates.
